from app.tools import content_generator
from app.tools import file_system # To confirm file creation if needed

# WORKSPACE_DIR is managed by the tools themselves, skills just pass filenames.

def skill_create_simple_text_report(
    report_title: str,
    report_body_content: str,
    output_filename: str = "report.txt"
) -> str | None:
    """
    Generates a simple text report and saves it to the workspace.
    Returns the path to the generated report if successful, None otherwise.
    """
    print(f"  [Skill] Creating simple text report titled '{report_title}' -> {output_filename}")

    # Ensure filename ends with .txt
    if not output_filename.lower().endswith(".txt"):
        output_filename += ".txt"
        print(f"  [Skill] Appended .txt to filename: {output_filename}")

    success = content_generator.generate_text_report(
        filename=output_filename,
        title=report_title,
        content=report_body_content
    )
    if success:
        # The file_system tool operates relative to WORKSPACE_DIR
        # So, if generate_text_report is successful, the file is in WORKSPACE_DIR/output_filename
        full_path = f"workspace/{output_filename}" # For confirmation message
        print(f"  [Skill] Text report successfully generated: {full_path}")
        return output_filename # Return relative path, consistent with tool inputs
    else:
        print(f"  [Skill] Failed to generate text report: {output_filename}")
        return None

def skill_create_simple_pdf_report(
    report_title: str,
    paragraphs: list[str],
    output_filename: str = "report.pdf"
) -> str | None:
    """
    Generates a simple PDF report and saves it to the workspace.
    Returns the path to the generated report if successful, None otherwise.
    """
    print(f"  [Skill] Creating simple PDF report titled '{report_title}' -> {output_filename}")

    if not output_filename.lower().endswith(".pdf"):
        output_filename += ".pdf"
        print(f"  [Skill] Appended .pdf to filename: {output_filename}")

    success = content_generator.generate_pdf_report_simple(
        filename=output_filename,
        title=report_title,
        text_content=paragraphs
    )
    if success:
        full_path = f"workspace/{output_filename}"
        print(f"  [Skill] PDF report successfully generated: {full_path}")
        return output_filename
    else:
        print(f"  [Skill] Failed to generate PDF report: {output_filename}")
        return None


if __name__ == '__main__':
    import os # For checking file existence in tests
    # Need to ensure workspace exists for standalone testing of skills
    if not os.path.exists("workspace"):
        os.makedirs("workspace")

    print("--- Testing Reporting Skills ---")

    # Test skill_create_simple_text_report
    print("\nTesting skill_create_simple_text_report:")
    txt_report_filename = "my_skill_text_report.txt"
    txt_report_path = skill_create_simple_text_report(
        report_title="Skill-Generated Text Report",
        report_body_content="This report was generated by a skill that uses a content generation tool.",
        output_filename=txt_report_filename
    )
    if txt_report_path:
        print(f"Text report skill succeeded. Output: {txt_report_path}")
        assert os.path.exists(os.path.join("workspace", txt_report_filename))
    else:
        print("Text report skill failed.")

    # Test skill_create_simple_pdf_report
    print("\nTesting skill_create_simple_pdf_report:")
    pdf_report_filename = "my_skill_pdf_report.pdf"
    pdf_paragraphs = [
        "This PDF was created by a skill.",
        "The skill called the content_generator tool.",
        "This demonstrates composing functionality."
    ]
    pdf_report_path = skill_create_simple_pdf_report(
        report_title="Skill-Generated PDF Report",
        paragraphs=pdf_paragraphs,
        output_filename=pdf_report_filename
    )
    if pdf_report_path:
        print(f"PDF report skill succeeded. Output: {pdf_report_path}")
        assert os.path.exists(os.path.join("workspace", pdf_report_filename))
    else:
        print("PDF report skill failed.")

    print("\n--- Reporting Skills Test Complete ---")
    # import shutil
    # if os.path.exists("workspace"):
    #     shutil.rmtree("workspace")
